version: '3.3'
services:

  db:
    image: 'postgres:${POSTGRES_VERSION}'
    restart: unless-stopped
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: var/lib/postgresql/data/pgdata
  app:
#    image: andvolkov/ya.entry:latest
    build: ../backend
    restart: unless-stopped
    command:
      uvicorn main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    depends_on:
      - db
  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app