"""initial

Revision ID: 556533be7244
Revises: 
Create Date: 2022-09-11 22:37:42.354374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '556533be7244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('parentId', sa.String(), nullable=True),
    sa.Column('type', postgresql.ENUM('file', 'folder', name='type'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['nodes.id'], name=op.f('fk__nodes__parentId__nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__nodes'))
    )
    op.create_index(op.f('ix__nodes__id'), 'nodes', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__nodes__id'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
