"""initial

Revision ID: 605b31431ada
Revises: 
Create Date: 2022-09-11 14:55:27.674852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '605b31431ada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', postgresql.ENUM('file', 'folder', name='type'), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__nodes'))
    )
    op.create_index(op.f('ix__nodes__id'), 'nodes', ['id'], unique=True)
    op.create_table('relations',
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('children_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['children_id'], ['nodes.id'], name=op.f('fk__relations__children_id__nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], name=op.f('fk__relations__parent_id__nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('parent_id', 'children_id', name=op.f('pk__relations')),
    sa.UniqueConstraint('parent_id', 'children_id', name=op.f('uq__relations__parent_id_children_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    op.drop_index(op.f('ix__nodes__id'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
